[build]
builder = "nixpacks"

[deploy]
startCommand = "npm start"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[environments.production.variables]
NODE_ENV = "production"
RAILWAY_ENVIRONMENT = "production"
MONGODB_URI = "mongodb://mongo:dfSakOiePzOactfHNwqrQNfHnRlqBVZX@mongodb.railway.internal:27017/condominio-sistema?authSource=admin"
MONGODB_DB = "condominio-sistema"
MONGO_INITDB_ROOT_PASSWORD = "dfSakOiePzOactfHNwqrQNfHnRlqBVZX"
MONGO_INITDB_ROOT_USERNAME = "mongo"
MONGO_PUBLIC_URL = "mongodb://mongo:dfSakOiePzOactfHNwqrQNfHnRlqBVZX@mongodb.railway.internal:27017/condominio-sistema?authSource=admin"
MONGO_URL = "mongodb://mongo:dfSakOiePzOactfHNwqrQNfHnRlqBVZX@mongodb.railway.internal:27017/condominio-sistema?authSource=admin"
MONGOHOST = "mongodb.railway.internal"
MONGOPASSWORD = "dfSakOiePzOactfHNwqrQNfHnRlqBVZX"
MONGOPORT = "27017"
MONGOUSER = "mongo"